// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.foamtec.fa.domain;

import com.foamtec.fa.domain.FirstArticle;
import com.foamtec.fa.domain.FirstArticleDataOnDemand;
import com.foamtec.fa.domain.FirstArticleIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FirstArticleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FirstArticleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FirstArticleIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FirstArticleIntegrationTest: @Transactional;
    
    @Autowired
    FirstArticleDataOnDemand FirstArticleIntegrationTest.dod;
    
    @Test
    public void FirstArticleIntegrationTest.testCountFirstArticles() {
        Assert.assertNotNull("Data on demand for 'FirstArticle' failed to initialize correctly", dod.getRandomFirstArticle());
        long count = FirstArticle.countFirstArticles();
        Assert.assertTrue("Counter for 'FirstArticle' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FirstArticleIntegrationTest.testFindFirstArticle() {
        FirstArticle obj = dod.getRandomFirstArticle();
        Assert.assertNotNull("Data on demand for 'FirstArticle' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FirstArticle' failed to provide an identifier", id);
        obj = FirstArticle.findFirstArticle(id);
        Assert.assertNotNull("Find method for 'FirstArticle' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'FirstArticle' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FirstArticleIntegrationTest.testFindAllFirstArticles() {
        Assert.assertNotNull("Data on demand for 'FirstArticle' failed to initialize correctly", dod.getRandomFirstArticle());
        long count = FirstArticle.countFirstArticles();
        Assert.assertTrue("Too expensive to perform a find all test for 'FirstArticle', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<FirstArticle> result = FirstArticle.findAllFirstArticles();
        Assert.assertNotNull("Find all method for 'FirstArticle' illegally returned null", result);
        Assert.assertTrue("Find all method for 'FirstArticle' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FirstArticleIntegrationTest.testFindFirstArticleEntries() {
        Assert.assertNotNull("Data on demand for 'FirstArticle' failed to initialize correctly", dod.getRandomFirstArticle());
        long count = FirstArticle.countFirstArticles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<FirstArticle> result = FirstArticle.findFirstArticleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'FirstArticle' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'FirstArticle' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FirstArticleIntegrationTest.testFlush() {
        FirstArticle obj = dod.getRandomFirstArticle();
        Assert.assertNotNull("Data on demand for 'FirstArticle' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FirstArticle' failed to provide an identifier", id);
        obj = FirstArticle.findFirstArticle(id);
        Assert.assertNotNull("Find method for 'FirstArticle' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFirstArticle(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'FirstArticle' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FirstArticleIntegrationTest.testMergeUpdate() {
        FirstArticle obj = dod.getRandomFirstArticle();
        Assert.assertNotNull("Data on demand for 'FirstArticle' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FirstArticle' failed to provide an identifier", id);
        obj = FirstArticle.findFirstArticle(id);
        boolean modified =  dod.modifyFirstArticle(obj);
        Integer currentVersion = obj.getVersion();
        FirstArticle merged = (FirstArticle)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'FirstArticle' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FirstArticleIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'FirstArticle' failed to initialize correctly", dod.getRandomFirstArticle());
        FirstArticle obj = dod.getNewTransientFirstArticle(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'FirstArticle' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'FirstArticle' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'FirstArticle' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FirstArticleIntegrationTest.testRemove() {
        FirstArticle obj = dod.getRandomFirstArticle();
        Assert.assertNotNull("Data on demand for 'FirstArticle' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FirstArticle' failed to provide an identifier", id);
        obj = FirstArticle.findFirstArticle(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'FirstArticle' with identifier '" + id + "'", FirstArticle.findFirstArticle(id));
    }
    
}
