// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.foamtec.fa.domain;

import com.foamtec.fa.domain.FirstArticleDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect FirstArticleDataOnDemand_Roo_Configurable {
    
    declare @type: FirstArticleDataOnDemand: @Configurable;
    
}
